[package]
name = "pprof"
version = "0.3.12"
authors = ["Yang Keao <keao.yang@yahoo.com>"]
edition = "2018"
license = "Apache-2.0"
description = "An internal perf tools for rust programs."
repository = "https://github.com/tikv/pprof-rs"
documentation = "https://docs.rs/pprof/"
readme = "README.md"

[features]
flamegraph = ["inferno"]
protobuf = ["prost", "bytes", "prost-derive", "prost-build"]

[dependencies]
backtrace = "0.3"
lazy_static = "1.4.0"
nix = "0.15.0"
quick-error = "1.2.2"
inferno = { version = "0.9.0", optional = true }
log = "0.4"
spin = "0.5.2"
rustc-demangle = "0.1.16"
tempfile = "3.1.0"
memmap = "0.7.0"
libc = { git = "https://github.com/rust-lang/libc" }
prost = { version="0.5", optional = true }
bytes = { version="0.4.12", optional = true }
prost-derive = { version="0.5", optional = true }

[dev-dependencies]
rand = "0.7.2"

[build-dependencies]
prost-build = { version = "0.5", optional = true }

[[example]]
name = "flamegraph"
required-features = ["flamegraph"]

[[example]]
name = "profile_proto"
required-features = ["protobuf"]

[[example]]
name = "multithread_flamegraph"
required-features = ["flamegraph"]

[package.metadata.docs.rs]
all-features = true
